### ISSUE TITLE
Mailing for connected chats

### ISSUE THREAD

**Issue by explesy** [antijob/neuro-parser#182]
Создать в Дажнго Админке, возможность для рассылки технических и иных сообщений в подклкюченные чаты. 

У нас есть список чатов, так что нужен инитерфейс для написания сообщения. Функционал:
- Возможностью добалвения размекти поддерживаемой телеграмом
- Выбор или наборт исключение чатов куда будет отправлено сообщение.

**Comment by Vldln** [comment]
1) Не забыть что сообщения будут отправляться только в чаты куда добавлен бот.
