### ISSUE TITLE
CI  с воркфлоу для тестов

### ISSUE THREAD

**Issue by Vldln** [antijob/neuro-parser#220]
Задача сделать  CI для гитхаб. Который:

1. Проводит тесты перед публикацией на стейдж и продакшн сервера
2. Проверяет при публикациях коммитов в PR

 При публикации на стейдж и продакшн при ошибках в тестах отменяет экшн
 При ошибках в  PR  выводит информацию в сниппете  PR  что тест не пройдет

**Comment by katsorio** [comment]
Closing as done in #227
